apiVersion: apps/v1
kind: Deployment
metadata:
  name: testpmd
spec:
  selector:
    matchLabels:
      app: testpmd
  replicas: 1
  template:
    metadata:
      labels:
        app: testpmd
    spec:
      containers:
      - name: testpmd
        image: vsperf/dpdkfwd:lakelse
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000