apiVersion: apps/v1
kind: Deployment
metadata:
  name: trex
spec:
  selector:
    matchLabels:
      app: trex
  replicas: 1
  template:
    metadata:
      labels:
        app: trex
    spec:
      containers:
      - name: trex
        image: vsperf/trex:lakelse
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000