{{- if eq .Values.kind "DaemonSet"}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prox
spec:
  selector:
    matchLabels: 
      app: prox
      key1: {{- .Values.nodeSelector.matchLables.key1}}
  template:
    metadata:
      labels:
        app: prox
    spec:
      containers:
      - name: prox
        image: opnfv/rapid:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
{{- end }}